[package]
name = "n-puzzle"
version = "0.1.0"
authors = ["cchudant <cchudant@student.42.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
rand = "0.8.4"
indexmap = "1.7.0"
structopt = "0.3.22"
